name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/setup-test-env
      - name: Build all packages
        shell: nix develop -c bash -eo pipefail -l {0}
        run: yarn build
      - id: npm-publish
        name: Publish wds to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
      - name: Push version tag to github
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.npm-publish.outputs.version }}
      - name: Publish Release to github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false